### Post "First product"
POST http://localhost:8080/
Content-Type: application/json

{
  "name": "test1",
  "protein": 55,
  "fats": 8,
  "carbohydrates": 0
}

### Post "Second product"

POST http://localhost:8080/
Content-Type: application/json

{
  "name": "test2",
  "protein": 11,
  "fats": 12,
  "carbohydrates": 13
}

### Get all the products
GET http://localhost:8080/

### Get product with specified name
GET http://localhost:8080/product/Chicken%20breast