CREATE TABLE IF NOT EXISTS product (
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(150) NOT NULL,
    protein INTEGER NOT NULL,
    fats INTEGER NOT NULL,
    carbohydrates INTEGER NOT NULL
);